version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mern-auth-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mern-auth
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - mern-network
    command: ["--bind_ip_all", "--auth"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/mern-auth --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  server:
    build: ./server
    container_name: mern-auth-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mernuser:mernpassword@mongo:27017/mern-auth?authSource=admin
      - JWT_SECRET=your_jwt_secret_key_here_change_this_in_production
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mern-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: mern-auth-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - mern-network

volumes:
  mongo_data:

networks:
  mern-network:
    driver: bridge