services:
  mongo:
    image: mongo:7.0
    container_name: mern-auth-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mern-auth
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-network
    command: ["--bind_ip_all"]

  server:
    build: ./server
    container_name: mern-auth-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mern-auth
      - JWT_SECRET=8f3a9b7c5e2d1f4a6c8e0b9a7d5f3e1a2c4e6b8a0d9f7e5c3a1b9d7f5e3a1c4e6b8a0d9f7e5c3a1b9d7f5e3a1c4e6b8a0
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mern-network
    # 完全移除健康检查
    # healthcheck: ...

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mern-auth-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
